### ISSUE TITLE
bump lib deps to php 8.0

### ISSUE THREAD

**Issue by amodliszewski** [laravel-validation-rules/country-codes#10]
It's impossible to use this lib with php 8.0 due to league/iso3166 having new major version for php 8.0

**Comment by clarkeash** [comment]
Hey @ssx can you tag a new major version when you get chance, as the php 8 changes are on master.

**Comment by ssx** [comment]
Tagged https://github.com/laravel-validation-rules/country-codes/releases/tag/v3.0.0

**Comment by clarkeash** [comment]
Thanks
