### ISSUE TITLE
PHP 8

### ISSUE THREAD

**Issue by clarkeash** [laravel-validation-rules/country-codes#6]
Hey Scott,

I would like to use this on a PHP 8 project, this would require updating `league/iso3166` to v3.0 which only supports PHP 7.3 and above which would mean this rule would need to drop support for 7.1 and 7.2. If you are okay with this I can submit a PR.

**Comment by clarkeash** [comment]
I just found https://github.com/spatie/laravel-validation-rules#countrycode so I will use that for now, but this still might be worth doing so I will leave open.

**Comment by ssx** [comment]
Of course buddy! Go for it :)

**Comment by clarkeash** [comment]
Closing in favour of #7
